version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:v1.9.0
    container_name: qdrant
    ports:
      - "6333:6333"
    environment:
      QDRANT__STORAGE__OPTIMIZE_MEM_USE: "true"
    volumes:
      - ./data/qdrant:/qdrant/storage
    mem_limit: 2g

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434" 
    volumes:
      - ./ollama:/root/.ollama
    mem_limit: 4g
    command: >
      sh -c "ollama serve &
             sleep 5 &&
             ollama pull llama3:3b-instruct-q4_0 &&
             tail -f /dev/null"

  rag-api:
    build: .
    container_name: rag-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - qdrant
      - ollama
